name = "InteractVanilla"
uuid = "e1d39746-8948-11e9-3b32-ef502038ee8c"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
